#!/bin/bash 


ping hx1.pa.msu.edu
ping hx2.pa.msu.edu
ping hx3.pa.msu.edu
ping hx4.pa.msu.edu
ping hx5.pa.msu.edu
ping hx6.pa.msu.edu
ping hx7.pa.msu.edu
ping hx8.pa.msu.edu
ping hx9.pa.msu.edu
ping hx10.pa.msu.edu
ping hx11.pa.msu.edu
ping hx12.pa.msu.edu
ping hx13.pa.msu.edu
ping hx14.pa.msu.edu
ping hx15.pa.msu.edu
ping hx16.pa.msu.edu
ping hx17.pa.msu.edu
ping hx18.pa.msu.edu
ping hx19.pa.msu.edu
ping hx20.pa.msu.edu
ping hx21.pa.msu.edu
ping hx22.pa.msu.edu
ping hx23.pa.msu.edu
ping hx24.pa.msu.edu
ping hx25.pa.msu.edu
ping hx26.pa.msu.edu
ping hx27.pa.msu.edu
ping hx28.pa.msu.edu
ping hx29.pa.msu.edu
ping hx30.pa.msu.edu
ping hx31.pa.msu.edu
ping hx32.pa.msu.edu
ping hx33.pa.msu.edu
ping hx34.pa.msu.edu
ping hx35.pa.msu.edu
ping hx36.pa.msu.edu
ping hx37.pa.msu.edu
ping hx38.pa.msu.edu
ping hx39.pa.msu.edu
ping hx40.pa.msu.edu
ping hx41.pa.msu.edu
ping hx42.pa.msu.edu
ping hx43.pa.msu.edu
ping hx44.pa.msu.edu
ping hx45.pa.msu.edu
ping hx46.pa.msu.edu
ping hx47.pa.msu.edu
ping hx48.pa.msu.edu
ping hx49.pa.msu.edu
ping hx50.pa.msu.edu
ping hx51.pa.msu.edu
ping hx52.pa.msu.edu
ping hx53.pa.msu.edu
ping hx54.pa.msu.edu
ping hx55.pa.msu.edu
