######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 8 11:13:44 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp
