######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 7 17:19:12 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += age.cpp
