python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 bhdcal0611-html5-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 bhdcal0611-WebKitNet-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 bhdcal0611-WebKitWeb-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 bhnal0611-html5-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 bhnal0611-WebKitNet-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 bhnal0611-WebKitWeb-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 bhnca0611-html5-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 bhnca0611-WebKitNet-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 bhnca0611-WebKitWeb-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 bhnfl0611-html5-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 bhnfl0611-WebKitNet-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 bhnfl0611-WebKitWeb-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 bhnoh0611-html5-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 bhnoh0611-WebKitNet-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 bhnoh0611-WebKitWeb-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 blngmt0611-html5-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 blngmt0611-WebKitNet-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 blngmt0611-WebKitWeb-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 bodcma0611-html5-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 bodcma0611-WebKitNet-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 bodcma0611-WebKitWeb-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 dldctx0611-html5-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 dldctx0611-WebKitNet-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 dldctx0611-WebKitWeb-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 edprmn0611-html5-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 edprmn0611-WebKitNet-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 edprmn0611-WebKitWeb-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 knwdmi0611-html5-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 knwdmi0611-WebKitNet-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 knwdmi0611-WebKitWeb-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 ladcca0611-html5-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 ladcca0611-WebKitNet-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 ladcca0611-WebKitWeb-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 mddcwi0611-html5-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 mddcwi0611-WebKitNet-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 mddcwi0611-WebKitWeb-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 nvdctn0611-html5-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 nvdctn0611-WebKitNet-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 nvdctn0611-WebKitWeb-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 pldcor0611-html5-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 pldcor0611-WebKitNet-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 pldcor0611-WebKitWeb-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 renonv0611-html5-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 renonv0611-WebKitNet-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 renonv0611-WebKitWeb-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 sldcla0611-html5-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 sldcla0611-WebKitNet-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 sldcla0611-WebKitWeb-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 sldcmo0611-html5-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 sldcmo0611-WebKitNet-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 sldcmo0611-WebKitWeb-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 slotca0611-html5-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 slotca0611-WebKitNet-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 slotca0611-WebKitWeb-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 spdcsc0611-html5-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 spdcsc0611-WebKitNet-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 spdcsc0611-WebKitWeb-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 twcca0611-html5-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 twcca0611-WebKitNet-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 twcca0611-WebKitWeb-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 twchi0611-html5-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 twchi0611-WebKitNet-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 twchi0611-WebKitWeb-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 twcny.nydc0611-html5-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 twcny.nydc0611-WebKitNet-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 twcny.nydc0611-WebKitWeb-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 twcny.sydc0611-html5-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 twcny.sydc0611-WebKitNet-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 twcny.sydc0611-WebKitWeb-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 twcoh0611-html5-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 twcoh0611-WebKitNet-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 twcoh0611-WebKitWeb-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 twcsc0611-html5-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 twcsc0611-WebKitNet-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 twcsc0611-WebKitWeb-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 twctx0611-html5-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 twctx0611-WebKitNet-vca.txt
python parse.py /home/bschoenrock/git/Insights/StaleSessions/ansible0611 twctx0611-WebKitWeb-vca.txt

