######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 7 17:07:04 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += HelloQt.C
